language: php

php:
  - 5.3
  - 5.4
  - hhvm

env:
 - APP_ENV=dev

branches:
  only:
    - develop
    - master

before_script:
 - pyrus install pear/PHP_Codesniffer
 - phpenv rehash
 - composer install

script:
 - phpunit --configuration src/test_suite.xml
