language: php

php:
  - 5.3

env:
 - APP_ENV=dev

before_script:
 - git submodule update --init --recursive
 - pyrus install pear/PHP_Codesniffer
 - phpenv rehash

script:
 - phpunit --configuration src/test_suite.xml
